blank_issues_enabled: true
contact_links:
  - name: TextIgniterJS
    url: https://mindfiredigital.github.io/TextIgniterJS/
    about: TextIgniterJS is a tool that allows developers to integrate HTML Editor using Typescript.
